### ISSUE TITLE
Ask for update

### ISSUE THREAD

**Issue by Kyck-02** [stm32duino/STM32LowPower#33]
Hello
When updating the library in platformio errors started because it mentions that certain functions that belong to low_power.h are not declared as attached in the following image, when using this programming environment should I define something else?
I tried the library on arduino and it works but going to Platformio doesn't finish loading the program, I am using STM32duino on both platforms.
Thank you for your attention
![asd](https://user-images.githubusercontent.com/68021176/87069337-a85f3880-c1dc-11ea-99e7-e64aaabbd2c8.png)

**Comment by fpistm** [comment]
Hi @Kyck-02 
unfortunately, I don't use nor support PIO, only Arduino IDE is supported.
There are some changes in this library and in the RTC one where both bsp previously in the core were moved in each library.
I guess your issue is linked to this. So you have to aligned your config. I guess you have the master of the core but not the one from this library.
I close this issue as not related to arduino usage.
